apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result
  template:
    metadata:
      labels:
        name: result
    spec:
      containers: 
        - image: mecit35/result-server-2
          name: result
          ports: 
            - containerPort: 80
          imagePullPolicy: Always
          
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
--- 
apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
spec:
  selector:
    name: result
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002